// <auto-generated />
using System;
using ClassroomManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassroomManagement.Migrations
{
    [DbContext(typeof(ClassroomManagementContext))]
    [Migration("20221228194159_InitialRecreate")]
    partial class InitialRecreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.Alunos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.Materias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MateriasName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Materias", (string)null);
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.ProfessorMateria", b =>
                {
                    b.Property<int>("MateriasId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessoresId")
                        .HasColumnType("int");

                    b.HasKey("MateriasId", "ProfessoresId");

                    b.HasIndex("ProfessoresId")
                        .IsUnique();

                    b.ToTable("ProfessorMateria", (string)null);
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.Professores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MateriasId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MateriasId");

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.Provas", b =>
                {
                    b.Property<int>("ProvasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvasId"));

                    b.Property<int>("AlunosId")
                        .HasColumnType("int");

                    b.Property<int>("MateriasId")
                        .HasColumnType("int");

                    b.Property<double>("Nota")
                        .HasColumnType("float");

                    b.HasKey("ProvasId");

                    b.HasIndex("AlunosId");

                    b.HasIndex("MateriasId");

                    b.ToTable("Provas", (string)null);
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.ProfessorMateria", b =>
                {
                    b.HasOne("GestãoDeSalaDeAula.Models.Materias", "Materia")
                        .WithMany("ProfessorMateria")
                        .HasForeignKey("MateriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestãoDeSalaDeAula.Models.Professores", "Professor")
                        .WithOne("ProfessorMateria")
                        .HasForeignKey("GestãoDeSalaDeAula.Models.ProfessorMateria", "ProfessoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.Professores", b =>
                {
                    b.HasOne("GestãoDeSalaDeAula.Models.Materias", "Materias")
                        .WithMany()
                        .HasForeignKey("MateriasId");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.Provas", b =>
                {
                    b.HasOne("GestãoDeSalaDeAula.Models.Alunos", "Aluno")
                        .WithMany("Provas")
                        .HasForeignKey("AlunosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestãoDeSalaDeAula.Models.Materias", "Materia")
                        .WithMany("Provas")
                        .HasForeignKey("MateriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.Alunos", b =>
                {
                    b.Navigation("Provas");
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.Materias", b =>
                {
                    b.Navigation("ProfessorMateria");

                    b.Navigation("Provas");
                });

            modelBuilder.Entity("GestãoDeSalaDeAula.Models.Professores", b =>
                {
                    b.Navigation("ProfessorMateria");
                });
#pragma warning restore 612, 618
        }
    }
}
